### ISSUE TITLE
few questions

### ISSUE THREAD

**Issue by countnazgul** [sammler/sammler#1]
Hi Stefan,

I had similar idea myself couple of year back but haven't moved it much after the initial few iterations - app that collects data from different sources with the option to add additional "collectors" as a separate modules (had working twitter and g+ collection). The idea behind this was to put the collected data in QV and perform some analysis that I've needed back then.

Think `sammler` is a very good idea especially for "test and validate technologies". In this case you'll have a decent data flow. 

Have a few questions:
  * How are you planning to use the data after this
  * Are you planning different storage options 
  * `sammler` client (where it can hook to the main stream from my machine)
  * what help you'll need

Thanks!
Stefan

**Comment by stefanwalther** [comment]
Hi,

thx for being interested in that project, you are the first one, hurray ;-)

I have just published some further details on the MVP and the first step I'd like to achieve:
https://github.com/sammler/sammler/blob/master/docs/mvp.md

It will take some time to get there, but I guess I'll be there before X-Mas. From that point in time it should be possible for others to contribute quite easily.
Right now I am building a lot of different building blocks which will make it much easier in the future to add new functionality, to speed up development without taking care of the infrastructure, deployment, logging, etc.

To answer your questions:

> How are you planning to use the data after this
As each service should follow the principle of being loosely coupled from the other services or plugin, every service should be able to store the data independently from other services. For the MVP and the sammler-middleware-github service I have chosen PostgreSql.
In general I foresee that a service is only exposing its data via REST (to other services and the outside world)

> Are you planning different storage options
Yes, definitely. See above.

> sammler client (where it can hook to the main stream from my machine)
Right now there is nothing such as a sammler client. If you talk about how to develop locally, it will just be a `docker-compose up`, then you have everything you need to create your own service.
I am planning to create something like a boilerplate (based on the best practices I am currently defining) using Yeoman, so that you can easily create your new service using node.js.
Later on the same should be possible for GoLang services (as especially in an IoT scenario) I'd like to use GoLang (e.g. just for performance reasons).

> what help you'll need
Right now, you help a lot just by being interested. Play stay tuned for another two or three weeks and come back ;-)

**Comment by countnazgul** [comment]
Thanks Stefan and good luck!

**Comment by stefanwalther** [comment]
Thx.
